all:
	javac -cp commons-math3-3.6.1.jar:. DoublePair.java
	javac -cp commons-math3-3.6.1.jar:. Analyzer.java
	javac -cp commons-math3-3.6.1.jar:. CurveFit.java
	javac -cp commons-math3-3.6.1.jar:. DoubleListPair.java

clean:
	rm *.class
